green-ecolution/green-ecolution-frontend

backend-client/package.json
API Docs have been updated in the backend green-ecolution/green-ecolution-backend@b06ce82. Please review if the changes are compatible with the frontend.
=> Update Backend API Client

frontend/src/api/backendApi.ts, frontend/src/components/map/MapMarker.tsx, frontend/src/components/map/MapSelectTreesModal.tsx, frontend/src/components/map/TreeMarker.tsx, frontend/src/hooks/useMapMouseSelect.ts, frontend/src/routeTree.gen.ts, frontend/src/routes/_protected/map/tree/new.tsx, frontend/src/routes/_protected/map/treecluster/select.tree.tsx, frontend/src/routes/_protected/tree/new.tsx, frontend/src/schema/newTreeSchema.ts
- create tree in map
- dragable marker of tree in map
- new form to add tree metadata
refs #74
=> feat: create tree in map

frontend/src/components/tree/TreeGeneralData.tsx, frontend/src/schema/newTreeSchema.ts
=> feat: remove height above sea level.

frontend/src/routes/_protected/tree/_formular/new.tsx
=> feat: load data after store is reset

CHANGELOG.md
=> docs: Added changelog

frontend/src/routes/logout.tsx
=> Redirect to start page on logout

frontend/src/api/backendApi.ts, frontend/src/routes/__root.tsx, frontend/src/routes/_protected.tsx, frontend/src/routes/login.tsx, frontend/src/store/user/types.ts, frontend/src/store/user/userStore.ts
Close #186 
Use with green-ecolution/green-ecolution-backend#138
1. Log in
2. Reduce refresh token session time in keycloak
3. Try to navigate in the app
4. You should be redirect to keycloak if your session is expired
=> feat: redirect to login if refresh token is invalid

frontend/vite.config.ts
=> fix: vite.config.ts (#213)

frontend/src/components/general/Modal.tsx, frontend/src/components/general/filter/Dialog.tsx, frontend/src/components/map/MapButtons.tsx
=> feature: add modal with linkt to create a new tree

frontend/src/components/layout/Navigation.tsx, frontend/src/components/startpage/QuickLinks.tsx, frontend/src/components/tree/TreeDashboard.tsx, frontend/src/routes/_protected/dashboard.tsx, frontend/src/routes/_protected/map.tsx
=> chore: rename »Baumkataster« to »Karte«

frontend/src/components/general/DetailedList.tsx, frontend/src/components/sensor/SensorDashboard.tsx, frontend/src/components/tree/TreeGeneralData.tsx, frontend/src/components/vehicle/VehicleDashboard.tsx
=> refactor: detailed list

frontend/src/components/map/marker/ClusterMarker.tsx
=> fix: show correct tree count of cluster on map

frontend/src/api/queries.ts, frontend/src/components/general/cards/EntitiesStatusCard.tsx, frontend/src/components/sensor/SensorDashboard.tsx, frontend/src/components/tree/TreeDashboard.tsx, frontend/src/components/treecluster/TreeClusterDashboard.tsx, frontend/src/components/vehicle/VehicleDashboard.tsx, frontend/src/components/watering-plan/WateringPlanDashboard.tsx, frontend/src/routes/_protected/sensors/$sensorId/index.tsx, frontend/src/routes/_protected/tree/$treeId.tsx, frontend/src/routes/_protected/treecluster/$treeclusterId/index.tsx, frontend/src/routes/_protected/treecluster/$treeclusterId/tree/$treeId.tsx, frontend/src/routes/_protected/vehicles/$vehicleId/index.tsx, frontend/src/routes/_protected/watering-plans/$wateringPlanId/index.tsx
- Fix breadcrumb-bug due to wrong caching in queries
- Unify and simplify data load on single views
- Fix bug in EntitiesStatusCard due to wrong ``
=> refactor: fix queries and simplify data load on views

frontend/src/api/backendApi.ts, frontend/src/api/queries.ts, frontend/src/components/map/marker/ShowRoutePreview.tsx, frontend/src/components/watering-plan/WateringPlanDashboard.tsx, frontend/src/routes/_protected/map/watering-plan/select.cluster.tsx, frontend/src/routes/_protected/watering-plans/$wateringPlanId/index.tsx, frontend/src/routes/_protected/watering-plans/_formular/new.tsx, frontend/src/routes/_protected/watering-plans/index.tsx
Test with green-ecolution/green-ecolution-backend#328
POC for downloading pgx route file. Missing style
=> feat: route preview

frontend/src/components/general/buttons/LinkButton.tsx, frontend/src/components/watering-plan/WateringPlanDashboard.tsx
=> feat: style download route button

.gitignore, frontend/src/components/general/form/FormForVehicle.tsx, frontend/src/components/vehicle/VehicleDashboard.tsx, frontend/src/components/vehicle/VehicleUpdate.tsx, frontend/src/routes/_protected/vehicles/$vehicleId/index.tsx, frontend/src/routes/_protected/vehicles/_formular/new.tsx, frontend/src/schema/vehicleSchema.ts, plugin-interface/.gitignore, plugin-interface/tsconfig.build.tsbuildinfo, plugin-interface/tsconfig.node.tsbuildinfo
=> feat: added vehicle weight

frontend/src/api/queries.ts, frontend/src/components/general/cards/UserCard.tsx, frontend/src/hooks/useDetailsForUser.ts, frontend/src/routes/_protected/team/index.tsx
=> feat: user status and role

frontend/src/components/map/MapMarker.tsx, frontend/src/components/map/marker/RouteMarker.tsx, frontend/src/components/map/marker/ShowRoutePreview.tsx
Close #329
Test with backend: https://github.com/green-ecolution/green-ecolution-backend/pull/349
=> feat: add route marker

frontend/src/routes/_protected/map/watering-plan/select.cluster.tsx
=> feat: show notice if no transporter was selected

frontend/src/routes/_protected/treecluster/$treeclusterId/tree/$treeId.tsx
=> fix: load correct data for TreeDashboard

frontend/src/components/sensor/SensorDashboard.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/_protected/sensors/$sensorId.tsx, frontend/src/routes/_protected/sensors/index.tsx
=> fix: do not use useSuspenseQuery for getting optional linked tree

frontend/src/components/general/Tabs.tsx, frontend/src/components/watering-plan/WateringPlanDashboard.tsx, frontend/src/components/watering-plan/WateringPlanRoutePreview.tsx
=> feat: preview route in dashboard

frontend/src/components/treecluster/TreeClusterDashboard.tsx
=> feat: add last watered value to treecluster dashboard

LICENSE, backend-client/package.json, frontend/package.json, package.json, plugin-interface/package.json
=> Use AGPL License

frontend/src/hooks/form/useTreeForm.ts
Test with: https://github.com/green-ecolution/green-ecolution-backend/pull/364
=> fix: invalidate treecluster query on tree create and update

frontend/src/api/queries.ts, frontend/src/routes/_protected/watering-plans/index.tsx
Test with backend https://github.com/green-ecolution/green-ecolution-backend/pull/388
Close #387 
First the base branch has to be merged
=> feat: add pagination to watering plan list

frontend/src/api/queries.ts, frontend/src/routes/_protected/vehicles/index.tsx
Test with backend: https://github.com/green-ecolution/green-ecolution-backend/pull/390
First the base branch has to me merged
=> feat: add pagination to vehicle list

frontend/src/components/general/cards/EntitiesStatusCard.tsx, frontend/src/components/tree/TabGeneralData.tsx, frontend/src/components/tree/TabWateringStatus.tsx, frontend/src/components/tree/TreeDashboard.tsx, frontend/src/hooks/details/useDetailsForWateringStatus.ts, frontend/tailwind.config.ts
Test with backend https://github.com/green-ecolution/green-ecolution-backend/pull/410
=> feat: expand watering status with value »just watered«

frontend/src/routes/_protected.tsx
=> fix: URL is incorrect if trying to open "deep" sites

frontend/src/components/tree/TabGeneralData.tsx, frontend/src/components/tree/TreeDashboard.tsx, frontend/src/components/tree/TreeUpdate.tsx, frontend/src/routes/_protected/trees/_formular/new.tsx, frontend/src/schema/treeSchema.ts
=> fix: show origin of tree

frontend/src/components/startpage/IntroductionSlider.tsx, frontend/src/components/startpage/KeyFacts.tsx, frontend/src/components/startpage/QuickLinks.tsx, frontend/src/css/components/splide.css, frontend/src/routes/index.tsx
=> fix: update content on startpage

frontend/src/components/map/Map.tsx, frontend/src/store/map/mapStore.ts, frontend/src/store/map/types.ts
close #203 
close #377 
This replaces old PR #377 due to history.
=> feat: add map boundaries

frontend/src/components/general/cards/TreeCard.tsx, frontend/src/components/tree/TabSensorData.tsx, frontend/src/components/treecluster/TreeClusterDashboard.tsx
=> fix: show correct tree card values, fix spelling mistake

frontend/src/routes/_protected/vehicles/_formular/new.tsx, frontend/src/schema/vehicleSchema.ts
=> fix: changed vehicle minimum water to 120

frontend/src/hooks/details/useDetailsForDrivingLicense.ts, frontend/src/routes/_protected/vehicles/_formular/new.tsx, frontend/src/schema/vehicleSchema.ts
Close #433 
Test with [438](https://github.com/green-ecolution/green-ecolution-backend/pull/438)
=> fix: forbid DrivingLicense Unknown

frontend/src/components/map/marker/MarkerList.tsx
=> fix: render issue in tree markers

frontend/src/components/general/filter/fieldsets/RegionFieldset.tsx
Test with backend: https://github.com/green-ecolution/green-ecolution-backend/pull/449
=> fix: update naming of region response

frontend/src/components/tree/TreeUpdate.tsx
=> fix: hide delete button for tbz trees

frontend/src/api/backendApi.ts, frontend/src/api/queries.ts, frontend/src/components/tree/TabWateringStatus.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/_protected/evaluations.tsx, frontend/src/routes/_protected/profile.tsx
Test with: https://github.com/green-ecolution/green-ecolution-backend/pull/448
refs #393 
Pipeline is failing because the backend PR is not in develop 👍 It can still be reviewed.
=> feat: show data on evaluation page

frontend/src/App.tsx, frontend/src/components/layout/ErrorFallback.tsx
Close #452 
To test this, just add
`throw new Error("Das ist ein Testfehler");`
to some page and navigate there.
=> feat: added error page

frontend/src/routes/_protected/settings/index.tsx, frontend/src/routes/_protected/settings/plugin/index.tsx
=> chore: update content on settings and plugins page

frontend/src/components/map/MapController.tsx, frontend/src/routes/_protected/map/route.tsx
=> fix: map controll view break on map move

frontend/src/routes/_protected/profile/index.tsx
=> feat: update profile description

frontend/src/components/general/cards/WateringPlanCard.tsx
=> fix: number of kilometers not correctly rounded
